[phases.setup]
nixPkgs = ['nodejs-18.x', 'postgresql']

[phases.install]
cmds = ["npm install --prefix backend"]

[phases.build]
cmds = ["cd frontend && npm install && npm run build"]

[start]
cmd = "cd backend && npm start"